spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: { password }
  sql:
    init:
      mode: always
  batch:
    job:
      name: movieJob

